### ISSUE TITLE
Missing gems, though installed

### ISSUE THREAD

**Issue by floli** [simonthum/ical2org#2]
Hello,

I'm not a ruby person, trying to install ical2org:

```
florian@asaru ~/scratch/calorg (git)-[master] % ruby ical2org.rb
/usr/lib/ruby/2.3.0/rubygems/dependency.rb:319:in `to_specs': Could not find 'ri_cal' (>= 0) among 34 total gem(s) (Gem::LoadError)
Checked in 'GEM_PATH=/home/florian/.gem/ruby/2.3.0:/usr/lib/ruby/gems/2.3.0', execute `gem env` for more information
        from /usr/lib/ruby/2.3.0/rubygems/dependency.rb:328:in `to_spec'
        from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
        from ical2org.rb:31:in `<main>'

florian@asaru ~/scratch/calorg (git)-[master] % gem env
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/florian/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/florian/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/2.3.0
     - /home/florian/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/florian/software/bin
     - /home/florian/.gem/ruby/2.3.0/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /usr/lib/jvm/default/bin
     - /usr/bin/site_perl
     - /usr/bin/vendor_perl
     - /usr/bin/core_perl

florian@asaru ~/scratch/calorg (git)-[master] % ll ~/.gem/ruby/2.3.0/gems 
insgesamt 0
drwxr-xr-x 1 florian florian  74  7. Jan 2016  activesupport-4.2.5
drwxr-xr-x 1 florian florian 122  7. Jan 2016  colorator-0.1
drwxr-xr-x 1 florian florian 124  7. Jan 2016  ffi-1.9.10
drwxr-xr-x 1 florian florian 232  7. Jan 2016  html-pipeline-2.2.2
drwxr-xr-x 1 florian florian  70  7. Jan 2016  i18n-0.7.0
drwxr-xr-x 1 florian florian  56  7. Jan 2016  jekyll-3.0.1
drwxr-xr-x 1 florian florian   6  7. Jan 2016  jekyll-mentions-1.0.0
drwxr-xr-x 1 florian florian   6  7. Jan 2016  jekyll-sass-converter-1.4.0
drwxr-xr-x 1 florian florian   6  7. Jan 2016  jekyll-watch-1.3.0
drwxr-xr-x 1 florian florian 174  7. Jan 2016  kramdown-1.9.0
drwxr-xr-x 1 florian florian  74  7. Jan 2016  liquid-3.0.6
drwxr-xr-x 1 florian florian 106  7. Jan 2016  listen-3.0.5
drwxr-xr-x 1 florian florian 232  7. Jan 2016  mercenary-0.3.5
drwxr-xr-x 1 florian florian 232  7. Jan 2016  mini_portile2-2.0.0
drwxr-xr-x 1 florian florian 562  7. Jan 2016  nokogiri-1.6.7.1
drwxr-xr-x 1 florian florian 162  7. Jan 2016  rb-fsevent-0.9.7
drwxr-xr-x 1 florian florian 130  7. Jan 2016  rb-inotify-0.9.5
drwxr-xr-x 1 florian florian 152  3. Aug 15:05 rical-1.2.1
drwxr-xr-x 1 florian florian  66  7. Jan 2016  rouge-1.10.1
drwxr-xr-x 1 florian florian 316  7. Jan 2016  safe_yaml-1.0.4
drwxr-xr-x 1 florian florian 284  7. Jan 2016  sass-3.4.20
drwxr-xr-x 1 florian florian 212  7. Jan 2016  thread_safe-0.3.5
drwxr-xr-x 1 florian florian 128  3. Aug 15:05 tzinfo-1.2.2
```

What could be the problem here?

**Comment by simonthum** [comment]
This is ruby being stupid at times. The gem is `ri_cal` not `rical`, sadly both exist.

I will see if I can put up a gemfile or something.

**Comment by floli** [comment]
Ok, installing ```ri_cal``` fixed it.
